// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuacofqojdpqmumklxah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1YWNvZnFvamRwcW11bWtseGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzIwMzQsImV4cCI6MjA3NDMwODAzNH0.301fgP8uhOJYjxsKkez_q5nlY6GWDrpB_NaiEgwxRdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});